<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div id="banner" class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-comment fa-2x mr-3"></i>
					Fale.
				</div>
				<div class="communicationItem">
					<i class="fas fa-comment fa-2x mr-3"></i>
					Ouça.
				</div>
				<div class="communicationItem">
					<i class="fas fa-comment fa-2x mr-3"></i>
					Converse.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form method="post" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" class="form-control" placeholder="E-mail" name="email">
				</div>
				<div class="col">
					<input type="password" class="form-control" placeholder="Senha" name="senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-secondary corbtn mb-2">Entrar</button>
				</div>
			</div>
			<?php if($this->view->login == 'erro'){ ?>
			<div class="row">
				<div class="col">
				<span class="text text-danger">E-mail ou senha inválido(s)!</span>
				</div>
			</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/logo.png" width="150px" />
				<h1 class="title">Seja ouvido!</h1>

				<a href="/inscreverse" class="btn btn-secondary corbtn btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>