<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <a href="/"><img src="/img/logo.png" width="100px" /></a>
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
            <?php if ($this->view->erroCadastro){
                echo "<small class='form-text text-danger'>Erro ao realizar o cadastro. Verifique os dados digitados</small>";
              }
              ?>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?php echo $this->view->usuario['nome'];?>" class="form-control" placeholder="Nome" name="nome">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?php echo $this->view->usuario['email'];?>" class="form-control" placeholder="E-mail" name="email">
              </div>

              <div class="form-group">
                <input type="password" value="<?php echo $this->view->usuario['senha'];?>" class="form-control" placeholder="Senha" name="senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-secondary corbtn btn-block">Inscrever-se</button>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>